language: 
 -  node_js

node_js: 
  - "12"

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/registration_test

before_script:
  - psql -c 'create database  registration_test;' -U postgres
  - psql -U postgres -d registration_test -a -f reg_table.sql

services:
  - postgresql
